version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-service
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --bind 0.0.0.0 --save 20 1 --loglevel warning


  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "8090:8001"
    volumes:
      - redis-insight-data:/db  

volumes:
  redis-data:
  redis-insight-data: